[GCC]drivers/usb/typec: google: max77759_contaminant: Fix function declaration not prototype
Reported by GCC 12.2

../drivers/usb/typec/tcpm/google/max77759_contaminant.c:479:13: error: function declaration isn't a prototype [-Werror=strict-prototypes]
  479 | static bool is_cc_open(cc_status)

Signed-off-by: Panchajanya1999 <kernel@panchajanya.dev>
(cherry picked from commit 9c455063d3c036b332285a2192b0ab05d83799be)