[GCC]drivers/soc/google: sched/rt: Fix missing return type
Reported by GCC 12.2. Fixes the following error:

../drivers/soc/google/vh/kernel/sched/rt.c:22:8: error: type defaults to 'int' in declaration of '___update_load_sum' [-Werror=implicit-int]
   22 | extern ___update_load_sum(u64 now, struct sched_avg *sa,
      |        ^~~~~~~~~~~~~~~~~~
../drivers/soc/google/vh/kernel/sched/rt.c:24:8: error: type defaults to 'int' in declaration of '___update_load_avg' [-Werror=implicit-int]
   24 | extern ___update_load_avg(struct sched_avg *sa, unsigned long load);
      |        ^~~~~~~~~~~~~~~~~~
  CC      sound/core/control.o
cc1: some warnings being treated as errors

Signed-off-by: Panchajanya1999 <kernel@panchajanya.dev>
(cherry picked from commit 5b8766e04a323d774b5d15128d50d46d5f1b7436)